apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: myapp/database
      property: username
  - secretKey: password
    remoteRef:
      key: myapp/database
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-cluster-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager-cluster
    kind: ClusterSecretStore
  target:
    name: example-cluster-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: myapp/api
      property: key
  - secretKey: api-secret
    remoteRef:
      key: myapp/api
      property: secret
